In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('country_vaccination_stats.csv')

In [3]:
df[:10]

     country        date  daily_vaccinations   vaccines
0  Argentina  12/29/2020                 NaN  Sputnik V
1  Argentina  12/30/2020             15656.0  Sputnik V
2  Argentina  12/31/2020             15656.0  Sputnik V
3  Argentina    1/1/2021             11070.0  Sputnik V
4  Argentina    1/2/2021              8776.0  Sputnik V
5  Argentina    1/3/2021              7400.0  Sputnik V
6  Argentina    1/4/2021              6483.0  Sputnik V
7  Argentina    1/5/2021              7984.0  Sputnik V
8  Argentina    1/6/2021              8173.0  Sputnik V
9  Argentina    1/7/2021              8363.0  Sputnik V

In [4]:
df[np.isnan(df['daily_vaccinations'])]

,country,date,daily_vaccinations,vaccines
0,Argentina,12/29/2020,NaN,Sputnik V
28,Austria,1/5/2021,NaN,Pfizer/BioNTech
48,Bahrain,12/23/2020,NaN,"Pfizer/BioNTech, Sinopharm"
77,Belgium,12/28/2020,NaN,Pfizer/BioNTech
103,Brazil,1/16/2021,NaN,Sinovac
113,Bulgaria,12/29/2020,NaN,"Moderna, Pfizer/BioNTech"
141,Canada,12/14/2020,NaN,"Moderna, Pfizer/BioNTech"
184,Chile,12/24/2020,NaN,Pfizer/BioNTech
217,China,12/15/2020,NaN,"CNBG, Sinovac"
254,Costa Rica,12/24/2020,NaN,Pfizer/BioNTech
280,Croatia,12/30/2020,NaN,Pfizer/BioNTech
307,Cyprus,1/6/2021,NaN,Pfizer/BioNTech
324,Czechia,12/27/2020,NaN,"Moderna, Pfizer/BioNTech"
354,Denmark,12/27/2020,NaN,"Moderna, Pfizer/BioNTech"
384,Ecuador,1/21/2021,NaN,Pfizer/BioNTech
386,England,12/20/2020,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech"
422,Estonia,12/28/2020,NaN,Pfizer/BioNTech
451,Finland,12/31/2020,NaN,Pfizer/BioNTech
477,France,1/4/2021,NaN,Pfizer/BioNTech
499,Germany,12/27/2020,NaN,"Moderna, Pfizer/BioNTech"
528,Gibraltar,1/10/2021,NaN,Pfizer/BioNTech
543,Greece,12/28/2020,NaN,Pfizer/BioNTech
572,Hungary,12/28/2020,NaN,Pfizer/BioNTech
600,Iceland,12/30/2020,NaN,"Moderna, Pfizer/BioNTech"
627,India,1/15/2021,NaN,"Covaxin, Covishield"
638,Indonesia,1/12/2021,NaN,Sinovac
652,Ireland,12/31/2020,NaN,Pfizer/BioNTech
677,Isle of Man,1/21/2021,NaN,Pfizer/BioNTech
682,Israel,12/19/2020,NaN,"Moderna, Pfizer/BioNTech"
720,Italy,12/27/2020,NaN,Pfizer/BioNTech
750,Kuwait,12/28/2020,NaN,Pfizer/BioNTech
751,Latvia,12/28/2020,NaN,Pfizer/BioNTech
780,Lithuania,12/25/2020,NaN,"Moderna, Pfizer/BioNTech"
812,Luxembourg,12/30/2020,NaN,Pfizer/BioNTech
838,Malta,12/28/2020,NaN,Pfizer/BioNTech
866,Mexico,12/24/2020,NaN,Pfizer/BioNTech
899,Netherlands,1/6/2021,NaN,"Moderna, Pfizer/BioNTech"
916,Northern Ireland,12/13/2020,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech"
959,Norway,12/27/2020,NaN,Pfizer/BioNTech
988,Oman,12/28/2020,NaN,Pfizer/BioNTech
1016,Panama,1/19/2021,NaN,Pfizer/BioNTech
1022,Poland,12/28/2020,NaN,Pfizer/BioNTech
1050,Portugal,12/27/2020,NaN,Pfizer/BioNTech
1079,Romania,12/28/2020,NaN,Pfizer/BioNTech
1108,Russia,12/15/2020,NaN,Sputnik V
1138,Saudi Arabia,1/6/2021,NaN,Pfizer/BioNTech
1150,Scotland,12/13/2020,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech"
1193,Serbia,1/8/2021,NaN,"Pfizer/BioNTech, Sinopharm, Sputnik V"
1211,Seychelles,1/9/2021,NaN,Sinopharm
1226,Singapore,1/11/2021,NaN,Pfizer/BioNTech
1238,Slovakia,1/4/2021,NaN,Pfizer/BioNTech
1256,Slovenia,1/3/2021,NaN,Pfizer/BioNTech
1278,Spain,1/4/2021,NaN,"Moderna, Pfizer/BioNTech"
1300,Sweden,12/27/2020,NaN,Pfizer/BioNTech
1322,Switzerland,12/23/2020,NaN,Pfizer/BioNTech
1352,Turkey,1/13/2021,NaN,Sinovac
1365,United Arab Emirates,1/5/2021,NaN,"Pfizer/BioNTech, Sinopharm"
1386,United Kingdom,12/20/2020,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech"
1422,United States,12/20/2020,NaN,"Moderna, Pfizer/BioNTech"
1459,Wales,12/13/2020,NaN,"Oxford/AstraZeneca, Pfizer/BioNTech"

In [5]:
min_vaccination_by_country = df.groupby('country')[['daily_vaccinations']].min()

In [6]:
min_vaccination_by_country

                      daily_vaccinations
country
Argentina                         6483.0
Austria                           3368.0
Bahrain                            943.0
Belgium                              1.0
Brazil                             112.0
Bulgaria                           472.0
Canada                             866.0
Chile                               51.0
China                           187500.0
Costa Rica                         240.0
Croatia                            989.0
Cyprus                             534.0
Czechia                           1822.0
Denmark                           1994.0
Ecuador                            108.0
England                          37625.0
Estonia                            309.0
Finland                            459.0
France                            5000.0
Germany                          19721.0
Gibraltar                          520.0
Greece                             549.0
Hungary                           1339.0
Iceland                             63.0
India                           112150.0
Indonesia                        11823.0
Ireland                            550.0
Isle of Man                         90.0
Israel                            6887.0
Italy                              926.0
Kuwait                               NaN
Latvia                             338.0
Lithuania                          311.0
Luxembourg                          62.0
Malta                              259.0
Mexico                            1300.0
Netherlands                       4000.0
Northern Ireland                  1563.0
Norway                             224.0
Oman                               817.0
Panama                               6.0
Poland                            4300.0
Portugal                          2791.0
Romania                            712.0
Russia                            3357.0
Saudi Arabia                     14153.0
Scotland                          3047.0
Serbia                            1150.0
Seychelles                         500.0
Singapore                         2800.0
Slovakia                           425.0
Slovenia                          1270.0
Spain                            41496.0
Sweden                            3859.0
Switzerland                       3000.0
Turkey                           67192.0
United Arab Emirates             30698.0
United Kingdom                   46423.0
United States                    57909.0
Wales                             1763.0

In [7]:
min_vaccination_by_country.fillna(0, inplace=True)

In [8]:
min_vaccination_by_country

                      daily_vaccinations
country
Argentina                         6483.0
Austria                           3368.0
Bahrain                            943.0
Belgium                              1.0
Brazil                             112.0
Bulgaria                           472.0
Canada                             866.0
Chile                               51.0
China                           187500.0
Costa Rica                         240.0
Croatia                            989.0
Cyprus                             534.0
Czechia                           1822.0
Denmark                           1994.0
Ecuador                            108.0
England                          37625.0
Estonia                            309.0
Finland                            459.0
France                            5000.0
Germany                          19721.0
Gibraltar                          520.0
Greece                             549.0
Hungary                           1339.0
Iceland                             63.0
India                           112150.0
Indonesia                        11823.0
Ireland                            550.0
Isle of Man                         90.0
Israel                            6887.0
Italy                              926.0
Kuwait                               0.0
Latvia                             338.0
Lithuania                          311.0
Luxembourg                          62.0
Malta                              259.0
Mexico                            1300.0
Netherlands                       4000.0
Northern Ireland                  1563.0
Norway                             224.0
Oman                               817.0
Panama                               6.0
Poland                            4300.0
Portugal                          2791.0
Romania                            712.0
Russia                            3357.0
Saudi Arabia                     14153.0
Scotland                          3047.0
Serbia                            1150.0
Seychelles                         500.0
Singapore                         2800.0
Slovakia                           425.0
Slovenia                          1270.0
Spain                            41496.0
Sweden                            3859.0
Switzerland                       3000.0
Turkey                           67192.0
United Arab Emirates             30698.0
United Kingdom                   46423.0
United States                    57909.0
Wales                             1763.0

In [15]:
df['daily_vaccinations'] = df.apply(lambda row: min_vaccination_by_country.loc[row['country']] if np.isnan(row['daily_vaccinations']) else row['daily_vaccinations'], axis=1)

In [16]:
df[:10]

     country        date  daily_vaccinations   vaccines
0  Argentina  12/29/2020              6483.0  Sputnik V
1  Argentina  12/30/2020             15656.0  Sputnik V
2  Argentina  12/31/2020             15656.0  Sputnik V
3  Argentina    1/1/2021             11070.0  Sputnik V
4  Argentina    1/2/2021              8776.0  Sputnik V
5  Argentina    1/3/2021              7400.0  Sputnik V
6  Argentina    1/4/2021              6483.0  Sputnik V
7  Argentina    1/5/2021              7984.0  Sputnik V
8  Argentina    1/6/2021              8173.0  Sputnik V
9  Argentina    1/7/2021              8363.0  Sputnik V

In [23]:
df.groupby('country').median().sort_values('daily_vaccinations')[-3:]

               daily_vaccinations
country
India                    173922.0
China                    276786.0
United States            378253.0

In [24]:
np.sum(df[df['date'] == '1/6/2021']['daily_vaccinations'])

1485255.0

Question 8

In [27]:
import re

In [65]:
url = '<url>http://xcd32112.smart_meter.com</url>'

In [71]:
print(re.sub(r'<url>https*://|</url>', '', url))

xcd32112.smart_meter.com